CFLAGS=-Wall -g

all: clean options ex1 ex2 ex7 ex8 ex9 ex10 ex11 ex12 ex13

options:
	@echo build options:
	@echo "CFLAGS	= $(CFLAGS)"
	@echo "CC	= $(CC)"

clean:
	rm -f ex1
	rm -f ex2
	rm -f ex7
	rm -f ex8
	rm -f ex9
	rm -f ex10
	rm -f ex11
	rm -f ex12
	rm -f ex13

.PHONY: all options clean
